const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const E={file:$('#fileInput'),drop:$('#dropZone'),emptyUpload:$('#emptyUploadBtn'),empty:$('#emptyState'),stage:$('#editorStage'),img:$('#editorImage'),box:$('#cropBox'),sourceName:$('#sourceName'),sourceInfo:$('#sourceInfo'),readout:$('#cropReadout'),w:$('#outputWidth'),h:$('#outputHeight'),lock:$('#lockRatio'),quality:$('#qualityRange'),qualityValue:$('#qualityValue'),qualityHint:$('#qualityHint'),name:$('#filenameInput'),keep:$('#keepOriginalName'),ext:$('#extensionLabel'),preview:$('#previewImage'),previewEmpty:$('#previewPlaceholder'),previewMeta:$('#previewMeta'),sumSize:$('#summarySize'),sumFormat:$('#summaryFormat'),sumQuality:$('#summaryQuality'),sumFile:$('#summaryFileSize'),download:$('#downloadBtn'),status:$('#statusMessage'),ratios:$('#ratioGrid'),presets:$('#presetGrid'),reset:$('#resetCropBtn'),fit:$('#fitBtn'),clear:$('#clearBtn')};
const apply=document.createElement('button');apply.id='applyCropBtn';apply.className='icon-button';apply.type='button';apply.textContent='确认裁切';apply.disabled=true;apply.title='确认当前裁切范围';$('.toolbar-actions')?.prepend(apply);E.apply=apply;
const S={file:null,srcUrl:null,previewUrl:null,nw:0,nh:0,bounds:null,crop:null,norm:null,outRatio:1200/750,drag:null,timer:0,token:0,dirty:false};
const types=new Set(['image/jpeg','image/png','image/webp']);
const clamp=(v,a,b)=>Math.min(Math.max(v,a),b);
const fmtBytes=n=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(n<10240?1:0)} KB`:`${(n/1048576).toFixed(2)} MB`;
const cleanName=n=>(String(n||'').trim().replace(/\.(jpe?g|png|webp)$/i,'').replace(/[\\/:*?"<>|]+/g,'_').replace(/^\.+|\.+$/g,'').replace(/\s+/g,'_').replace(/_+/g,'_').replace(/^_+|_+$/g,'')||'image');
const format=()=>($('input[name="format"]:checked')?.value||'webp');
const mime=()=>({jpg:'image/jpeg',png:'image/png',webp:'image/webp'})[format()];
const ext=()=>({jpg:'jpg',png:'png',webp:'webp'})[format()];
const status=(m,k='')=>{E.status.textContent=m;E.status.className=`status-message${k?` ${k}`:''}`};
function validDims(){const w=Number(E.w.value),h=Number(E.h.value);return Number.isInteger(w)&&w>0&&w<=12000&&Number.isInteger(h)&&h>0&&h<=12000?[w,h]:null}
function outRatio(){const d=validDims();return d?d[0]/d[1]:S.outRatio||1}
function summary(){const f=format();E.sumSize.textContent=`${E.w.value||0} × ${E.h.value||0}`;E.sumFormat.textContent=f.toUpperCase();E.sumQuality.textContent=f==='png'?'无损':`${E.quality.value}%`;E.ext.textContent=`.${ext()}`;E.qualityValue.textContent=f==='png'?'无损':`${E.quality.value}%`;E.quality.disabled=f==='png';E.qualityHint.textContent=f==='png'?'PNG 为无损输出；缩小尺寸可有效降低体积。':'WebP 推荐用于网页；80% 通常兼顾清晰度与档案大小。'}
function bounds(){if(!S.file||E.img.style.display==='none')return null;const a=E.stage.getBoundingClientRect(),b=E.img.getBoundingClientRect();return{x:b.left-a.left,y:b.top-a.top,width:b.width,height:b.height}}
function fitAspect(r,b,a){if(!r||!b||!a||!Number.isFinite(a))return r;const cx=r.x+r.width/2,cy=r.y+r.height/2;let w=r.width,h=r.height;if(w/h>a)w=h*a;else h=w/a;if(w>b.width){w=b.width;h=w/a}if(h>b.height){h=b.height;w=h*a}return{x:clamp(cx-w/2,b.x,b.x+b.width-w),y:clamp(cy-h/2,b.y,b.y+b.height-h),width:w,height:h}}
function saveNorm(){if(!S.bounds||!S.crop)return;const b=S.bounds,c=S.crop;S.norm={x:(c.x-b.x)/b.width,y:(c.y-b.y)/b.height,width:c.width/b.width,height:c.height/b.height}}
function drawCrop(){if(!S.crop)return;const c=S.crop;Object.assign(E.box.style,{left:`${c.x}px`,top:`${c.y}px`,width:`${c.width}px`,height:`${c.height}px`});E.box.hidden=false;const b=S.bounds;if(b)E.readout.textContent=`${Math.round(c.width/b.width*S.nw)} × ${Math.round(c.height/b.height*S.nh)}px`}
function dirty(msg='已调整裁切范围，请按「确认裁切」。'){if(!S.file)return;S.dirty=true;E.apply.disabled=false;E.download.disabled=true;status(msg)}
function conformCrop(msg){if(!S.file)return;S.bounds=bounds();if(!S.bounds)return;S.crop=fitAspect(S.crop||S.bounds,S.bounds,outRatio());saveNorm();drawCrop();if(msg)dirty(msg)}
function resetCrop(initial=false){if(!S.file)return;S.bounds=bounds();const b=S.bounds;if(!b||b.width<2||b.height<2)return;const p=Math.min(24,Math.max(8,Math.min(b.width,b.height)*.05)),inner={x:b.x+p,y:b.y+p,width:b.width-p*2,height:b.height-p*2};S.crop=fitAspect(inner,inner,outRatio());S.crop.x=inner.x+(inner.width-S.crop.width)/2;S.crop.y=inner.y+(inner.height-S.crop.height)/2;saveNorm();drawCrop();if(!initial)dirty('已重置裁切范围，请按「确认裁切」。')}
function restore(){if(!S.norm||!S.bounds)return false;const b=S.bounds,n=S.norm;S.crop={x:b.x+n.x*b.width,y:b.y+n.y*b.height,width:n.width*b.width,height:n.height*b.height};S.crop=fitAspect(S.crop,b,outRatio());drawCrop();return true}
function sourceCrop(crop=S.crop){const b=S.bounds,c=crop;if(!b||!c)return null;return{sx:(c.x-b.x)/b.width*S.nw,sy:(c.y-b.y)/b.height*S.nh,sw:c.width/b.width*S.nw,sh:c.height/b.height*S.nh}}
function toBlob(canvas){return new Promise((res,rej)=>canvas.toBlob(b=>b?res(b):rej(new Error('浏览器无法输出这个图片格式。')),mime(),format()==='png'?undefined:Number(E.quality.value)/100))}
async function render(quiet=true){if(!S.file||!S.crop)return null;const d=validDims();if(!d){E.download.disabled=true;if(!quiet)status('请输入 1～12000 之间的有效宽高。','error');return null}const token=++S.token;try{const crop=fitAspect(S.crop,S.bounds,d[0]/d[1]),c=sourceCrop(crop);if(!c||c.sw<=0||c.sh<=0)throw new Error('裁切区域无效，请重新调整。');const canvas=document.createElement('canvas');canvas.width=d[0];canvas.height=d[1];const x=canvas.getContext('2d',{alpha:mime()!=='image/jpeg'});x.imageSmoothingEnabled=true;x.imageSmoothingQuality='high';if(mime()==='image/jpeg'){x.fillStyle='#fff';x.fillRect(0,0,canvas.width,canvas.height)}x.drawImage(E.img,c.sx,c.sy,c.sw,c.sh,0,0,canvas.width,canvas.height);const blob=await toBlob(canvas);if(token!==S.token)return null;if(S.previewUrl)URL.revokeObjectURL(S.previewUrl);S.previewUrl=URL.createObjectURL(blob);E.preview.src=S.previewUrl;E.preview.style.display='block';E.previewEmpty.style.display='none';E.previewMeta.textContent=`${d[0]} × ${d[1]}  |  ${format().toUpperCase()}  |  ${fmtBytes(blob.size)}`;E.sumFile.textContent=fmtBytes(blob.size);E.download.disabled=false;summary();if(!quiet)status('裁切已确认，图片不会变形，可以直接下载部署。','success');return blob}catch(e){console.error(e);E.download.disabled=true;status(e.message||'图片处理失败，请重试。','error');return null}}
function schedule(){summary();if(!S.file||S.dirty)return;clearTimeout(S.timer);S.timer=setTimeout(()=>render(true),160)}
async function confirmCrop(){if(!S.file)return;conformCrop();S.dirty=false;E.apply.disabled=true;await render(false)}
function clear(show=true){if(S.srcUrl)URL.revokeObjectURL(S.srcUrl);if(S.previewUrl)URL.revokeObjectURL(S.previewUrl);Object.assign(S,{file:null,srcUrl:null,previewUrl:null,nw:0,nh:0,bounds:null,crop:null,norm:null,drag:null,dirty:false});E.img.removeAttribute('src');E.img.style.display='none';E.box.hidden=true;E.empty.style.display='flex';E.preview.removeAttribute('src');E.preview.style.display='none';E.previewEmpty.style.display='block';E.previewMeta.textContent='—';E.sumFile.textContent='—';E.sourceName.textContent='尚未选择图片';E.sourceInfo.textContent='—';E.readout.textContent='—';E.file.value='';E.reset.disabled=E.fit.disabled=E.clear.disabled=E.apply.disabled=E.download.disabled=true;if(show)status('已清除图片。')}
async function load(file){if(!file)return;if(!types.has(file.type)){status('目前仅支持 JPG、PNG、WebP。','error');return}clear(false);S.file=file;S.srcUrl=URL.createObjectURL(file);E.sourceName.textContent=file.name;E.sourceInfo.textContent=fmtBytes(file.size);E.name.value=cleanName(file.name);E.keep.checked=false;E.name.disabled=false;status('正在读取图片…');await new Promise((res,rej)=>{E.img.onload=res;E.img.onerror=rej;E.img.src=S.srcUrl});S.nw=E.img.naturalWidth;S.nh=E.img.naturalHeight;if(!S.nw||!S.nh)throw new Error('无法读取图片');E.sourceInfo.textContent=`${S.nw} × ${S.nh}  |  ${fmtBytes(file.size)}`;E.empty.style.display='none';E.img.style.display='block';E.reset.disabled=E.fit.disabled=E.clear.disabled=false;E.w.value=S.nw;E.h.value=S.nh;S.outRatio=S.nw/S.nh;summary();requestAnimationFrame(()=>requestAnimationFrame(async()=>{S.bounds=bounds();resetCrop(true);S.dirty=false;E.apply.disabled=true;await render(true);status('图片已载入。设定尺寸后裁切框会自动匹配比例。','success')}))}
function aspect(v,btn){$$('.ratio-btn').forEach(x=>x.classList.toggle('active',x===btn));const d=validDims();if(v!=='free'){const a=Number(v);if(d&&Number.isFinite(a)){E.h.value=Math.max(1,Math.round(d[0]/a));S.outRatio=a}}else if(d)S.outRatio=d[0]/d[1];summary();if(S.file)conformCrop('裁切比例已更新，请按「确认裁切」。')}
function dim(changed){let d=validDims();if(!d){E.download.disabled=true;status('请输入有效的输出尺寸。','error');summary();return}if(E.lock.checked){const r=S.outRatio||d[0]/d[1];if(changed==='w')E.h.value=Math.max(1,Math.round(Number(E.w.value)/r));else E.w.value=Math.max(1,Math.round(Number(E.h.value)*r))}d=validDims();if(!d)return;S.outRatio=d[0]/d[1];summary();if(S.file)conformCrop('输出尺寸已变更，请按「确认裁切」。')}
function preset(b){E.w.value=b.dataset.width;E.h.value=b.dataset.height;S.outRatio=Number(b.dataset.width)/Number(b.dataset.height);summary();if(S.file)conformCrop('已套用网页尺寸，请按「确认裁切」。')}
function outName(){const base=E.keep.checked&&S.file?cleanName(S.file.name):cleanName(E.name.value);return `${base}.${ext()}`}
async function download(){if(S.dirty)await confirmCrop();const blob=await render(false);if(!blob)return;const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=outName();document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);status(`已下载：${a.download}`,'success')}
function startDrag(e){if(!S.crop)return;e.preventDefault();S.drag={id:e.pointerId,h:e.target.dataset.handle||'',x:e.clientX,y:e.clientY,c:{...S.crop}};E.box.setPointerCapture?.(e.pointerId)}
function moveDrag(e){const d=S.drag,b=S.bounds;if(!d||e.pointerId!==d.id||!b)return;e.preventDefault();const dx=e.clientX-d.x,dy=e.clientY-d.y,c=d.c,R=b.x+b.width,B=b.y+b.height;if(!d.h){S.crop={...c,x:clamp(c.x+dx,b.x,R-c.width),y:clamp(c.y+dy,b.y,B-c.height)}}else{const west=d.h.includes('w'),north=d.h.includes('n'),min=36,a=outRatio();let l=c.x,t=c.y,r=c.x+c.width,bot=c.y+c.height;if(west)l=clamp(c.x+dx,b.x,r-min);else r=clamp(r+dx,l+min,R);if(north)t=clamp(c.y+dy,b.y,bot-min);else bot=clamp(bot+dy,t+min,B);S.crop=fitAspect({x:l,y:t,width:r-l,height:bot-t},b,a)}saveNorm();drawCrop()}
function endDrag(e){if(!S.drag||e.pointerId!==S.drag.id)return;S.drag=null;saveNorm();dirty()}
const open=()=>E.file.click();E.drop.onclick=open;E.emptyUpload.onclick=open;E.file.onchange=()=>load(E.file.files?.[0]).catch(e=>status(e.message,'error'));
['dragenter','dragover'].forEach(t=>E.drop.addEventListener(t,e=>{e.preventDefault();E.drop.classList.add('dragging')}));['dragleave','drop'].forEach(t=>E.drop.addEventListener(t,e=>{e.preventDefault();E.drop.classList.remove('dragging')}));E.drop.addEventListener('drop',e=>load(e.dataTransfer?.files?.[0]));
E.ratios.onclick=e=>{const b=e.target.closest('.ratio-btn');if(b)aspect(b.dataset.aspect,b)};E.w.oninput=()=>dim('w');E.h.oninput=()=>dim('h');E.lock.onchange=()=>{const d=validDims();if(d)S.outRatio=d[0]/d[1];if(S.file)conformCrop('比例锁定已更新，请按「确认裁切」。')};$$('input[name="format"]').forEach(r=>r.onchange=schedule);E.quality.oninput=schedule;E.keep.onchange=()=>{if(!S.file)return;E.name.disabled=E.keep.checked;if(E.keep.checked)E.name.value=cleanName(S.file.name)};E.presets.onclick=e=>{const b=e.target.closest('button[data-width]');if(b)preset(b)};E.box.onpointerdown=startDrag;window.addEventListener('pointermove',moveDrag,{passive:false});window.addEventListener('pointerup',endDrag);window.addEventListener('pointercancel',endDrag);E.reset.onclick=()=>resetCrop();E.fit.onclick=()=>{S.norm=null;S.bounds=bounds();resetCrop()};E.clear.onclick=()=>clear();E.apply.onclick=confirmCrop;E.download.onclick=download;
new ResizeObserver(()=>{if(!S.file)return;const n=S.norm?{...S.norm}:null;S.bounds=bounds();S.norm=n;if(!restore())resetCrop(true);if(!S.dirty)schedule()}).observe(E.stage);
window.addEventListener('beforeunload',()=>{if(S.srcUrl)URL.revokeObjectURL(S.srcUrl);if(S.previewUrl)URL.revokeObjectURL(S.previewUrl)});
const webp=$('input[name="format"][value="webp"]');if(webp)webp.checked=true;summary();
