const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const E={file:$('#fileInput'),drop:$('#dropZone'),emptyUpload:$('#emptyUploadBtn'),empty:$('#emptyState'),stage:$('#editorStage'),img:$('#editorImage'),box:$('#cropBox'),sourceName:$('#sourceName'),sourceInfo:$('#sourceInfo'),readout:$('#cropReadout'),w:$('#outputWidth'),h:$('#outputHeight'),lock:$('#lockRatio'),quality:$('#qualityRange'),qualityValue:$('#qualityValue'),qualityHint:$('#qualityHint'),name:$('#filenameInput'),keep:$('#keepOriginalName'),ext:$('#extensionLabel'),preview:$('#previewImage'),previewEmpty:$('#previewPlaceholder'),previewMeta:$('#previewMeta'),sumSize:$('#summarySize'),sumFormat:$('#summaryFormat'),sumQuality:$('#summaryQuality'),sumFile:$('#summaryFileSize'),download:$('#downloadBtn'),status:$('#statusMessage'),ratios:$('#ratioGrid'),presets:$('#presetGrid'),reset:$('#resetCropBtn'),fit:$('#fitBtn'),clear:$('#clearBtn')};
const S={file:null,srcUrl:null,previewUrl:null,nw:0,nh:0,bounds:null,crop:null,norm:null,aspect:null,outRatio:1200/750,drag:null,timer:0,token:0};
const types=new Set(['image/jpeg','image/png','image/webp']);
const clamp=(v,a,b)=>Math.min(Math.max(v,a),b);
const fmtBytes=n=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(n<10240?1:0)} KB`:`${(n/1048576).toFixed(2)} MB`;
const cleanName=n=>(String(n).trim().replace(/\.(jpe?g|png|webp)$/i,'').replace(/[\\/:*?"<>|]+/g,'_').replace(/^\.+|\.+$/g,'').replace(/\s+/g,'_').replace(/_+/g,'_').replace(/^_+|_+$/g,'')||'image');
const format=()=>($('input[name="format"]:checked')?.value||'jpg');
const mime=()=>({jpg:'image/jpeg',png:'image/png',webp:'image/webp'})[format()];
const ext=()=>({jpg:'jpg',png:'png',webp:'webp'})[format()];
const status=(m,k='')=>{E.status.textContent=m;E.status.className=`status-message${k?` ${k}`:''}`};
function summary(){const f=format();E.sumSize.textContent=`${E.w.value||0} × ${E.h.value||0}`;E.sumFormat.textContent=f.toUpperCase();E.sumQuality.textContent=f==='png'?'无损':`${E.quality.value}%`;E.ext.textContent=`.${ext()}`;E.qualityValue.textContent=f==='png'?'无损':`${E.quality.value}%`;E.quality.disabled=f==='png';E.qualityHint.textContent=f==='png'?'PNG 为无损输出，品质滑杆不生效；缩小尺寸可有效降低体积。':'品质越低档案越小；80% 通常适合网页使用。'}
function bounds(){if(!S.file||E.img.style.display==='none')return null;const a=E.stage.getBoundingClientRect(),b=E.img.getBoundingClientRect();return{x:b.left-a.left,y:b.top-a.top,width:b.width,height:b.height}}
function saveNorm(){if(!S.bounds||!S.crop)return;const b=S.bounds,c=S.crop;S.norm={x:(c.x-b.x)/b.width,y:(c.y-b.y)/b.height,width:c.width/b.width,height:c.height/b.height}}
function fitAspect(r,b,a){let w=Math.min(r.width,b.width),h=w/a;if(h>b.height){h=b.height;w=h*a}return{x:clamp(r.x,b.x,b.x+b.width-w),y:clamp(r.y,b.y,b.y+b.height-h),width:w,height:h}}
function drawCrop(){if(!S.crop)return;const c=S.crop;Object.assign(E.box.style,{left:`${c.x}px`,top:`${c.y}px`,width:`${c.width}px`,height:`${c.height}px`});E.box.hidden=false;const b=S.bounds;if(b){E.readout.textContent=`${Math.round(c.width/b.width*S.nw)} × ${Math.round(c.height/b.height*S.nh)}px`}}
function resetCrop(render=true){if(!S.file)return;S.bounds=bounds();const b=S.bounds;if(!b||b.width<2)return;const p=Math.min(24,Math.max(8,Math.min(b.width,b.height)*.05));let r={x:b.x+p,y:b.y+p,width:b.width-p*2,height:b.height-p*2};if(S.aspect){r=fitAspect(r,{x:b.x+p,y:b.y+p,width:b.width-p*2,height:b.height-p*2},S.aspect);r.x=b.x+(b.width-r.width)/2;r.y=b.y+(b.height-r.height)/2}S.crop=r;saveNorm();drawCrop();if(render)schedule()}
function restore(){if(!S.norm||!S.bounds)return false;const b=S.bounds,n=S.norm;S.crop={x:b.x+n.x*b.width,y:b.y+n.y*b.height,width:n.width*b.width,height:n.height*b.height};if(S.aspect)S.crop=fitAspect(S.crop,b,S.aspect);drawCrop();return true}
function sourceCrop(){const b=S.bounds,c=S.crop;if(!b||!c)return null;return{sx:(c.x-b.x)/b.width*S.nw,sy:(c.y-b.y)/b.height*S.nh,sw:c.width/b.width*S.nw,sh:c.height/b.height*S.nh}}
function validDims(){const w=Number(E.w.value),h=Number(E.h.value);return Number.isInteger(w)&&w>0&&w<=12000&&Number.isInteger(h)&&h>0&&h<=12000?[w,h]:null}
function toBlob(canvas){return new Promise((res,rej)=>canvas.toBlob(b=>b?res(b):rej(new Error('浏览器无法输出这个图片格式。')),mime(),format()==='png'?undefined:Number(E.quality.value)/100))}
async function render(quiet=true){if(!S.file||!S.crop)return null;const d=validDims();if(!d){E.download.disabled=true;if(!quiet)status('请输入 1～12000 之间的有效宽高。','error');return null}const token=++S.token;try{const c=sourceCrop();if(!c||c.sw<=0||c.sh<=0)throw new Error('裁切区域无效，请重新调整。');const canvas=document.createElement('canvas');canvas.width=d[0];canvas.height=d[1];const x=canvas.getContext('2d',{alpha:mime()!=='image/jpeg'});x.imageSmoothingEnabled=true;x.imageSmoothingQuality='high';if(mime()==='image/jpeg'){x.fillStyle='#fff';x.fillRect(0,0,canvas.width,canvas.height)}x.drawImage(E.img,c.sx,c.sy,c.sw,c.sh,0,0,canvas.width,canvas.height);const blob=await toBlob(canvas);if(token!==S.token)return null;if(S.previewUrl)URL.revokeObjectURL(S.previewUrl);S.previewUrl=URL.createObjectURL(blob);E.preview.src=S.previewUrl;E.preview.style.display='block';E.previewEmpty.style.display='none';E.previewMeta.textContent=`${d[0]} × ${d[1]}  |  ${format().toUpperCase()}  |  ${fmtBytes(blob.size)}`;E.sumFile.textContent=fmtBytes(blob.size);E.download.disabled=false;summary();if(!quiet)status('处理完成，可以下载。','success');return blob}catch(e){console.error(e);E.download.disabled=true;status(e.message||'图片处理失败，请重试。','error');return null}}
function schedule(){summary();if(!S.file)return;clearTimeout(S.timer);S.timer=setTimeout(()=>render(true),180)}
function clear(show=true){if(S.srcUrl)URL.revokeObjectURL(S.srcUrl);if(S.previewUrl)URL.revokeObjectURL(S.previewUrl);Object.assign(S,{file:null,srcUrl:null,previewUrl:null,nw:0,nh:0,bounds:null,crop:null,norm:null,drag:null});E.img.removeAttribute('src');E.img.style.display='none';E.box.hidden=true;E.empty.style.display='flex';E.preview.removeAttribute('src');E.preview.style.display='none';E.previewEmpty.style.display='block';E.previewMeta.textContent='—';E.sumFile.textContent='—';E.sourceName.textContent='尚未选择图片';E.sourceInfo.textContent='—';E.readout.textContent='—';E.file.value='';E.reset.disabled=E.fit.disabled=E.clear.disabled=E.download.disabled=true;if(show)status('已清除图片。')}
async function load(file){if(!file)return;if(!types.has(file.type)){status('目前仅支持 JPG、PNG、WebP。','error');return}clear(false);S.file=file;S.srcUrl=URL.createObjectURL(file);E.sourceName.textContent=file.name;E.sourceInfo.textContent=fmtBytes(file.size);E.name.value=cleanName(file.name);E.keep.checked=false;E.name.disabled=false;status('正在读取图片…');await new Promise((res,rej)=>{E.img.onload=res;E.img.onerror=rej;E.img.src=S.srcUrl});S.nw=E.img.naturalWidth;S.nh=E.img.naturalHeight;if(!S.nw)throw new Error('无法读取图片');E.sourceInfo.textContent=`${S.nw} × ${S.nh}  |  ${fmtBytes(file.size)}`;E.empty.style.display='none';E.img.style.display='block';E.reset.disabled=E.fit.disabled=E.clear.disabled=false;E.w.value=S.nw;E.h.value=S.nh;S.outRatio=S.nw/S.nh;summary();requestAnimationFrame(()=>requestAnimationFrame(()=>{S.bounds=bounds();resetCrop(false);status('图片已载入，可拖动裁切框。','success');schedule()}))}
function aspect(v,btn){$$('.ratio-btn').forEach(x=>x.classList.toggle('active',x===btn));S.aspect=v==='free'?null:Number(v);if(!S.file)return;if(S.aspect){S.bounds=bounds();S.crop=fitAspect(S.crop||S.bounds,S.bounds,S.aspect);if(E.lock.checked){E.h.value=Math.max(1,Math.round(Number(E.w.value)/S.aspect));S.outRatio=S.aspect}}saveNorm();drawCrop();schedule()}
function dim(changed){const d=validDims();if(!d){E.download.disabled=true;status('请输入有效的输出尺寸。','error');summary();return}if(E.lock.checked){const r=S.outRatio||d[0]/d[1];if(changed==='w')E.h.value=Math.max(1,Math.round(d[0]/r));else E.w.value=Math.max(1,Math.round(d[1]*r))}else S.outRatio=Number(E.w.value)/Number(E.h.value);schedule()}
function preset(b){E.w.value=b.dataset.width;E.h.value=b.dataset.height;S.outRatio=Number(b.dataset.width)/Number(b.dataset.height);schedule()}
function outName(){const base=E.keep.checked&&S.file?cleanName(S.file.name):cleanName(E.name.value);return `${base}.${ext()}`}
async function download(){const blob=await render(false);if(!blob)return;const a=document.createElement('a'),u=URL.createObjectURL(blob);a.href=u;a.download=outName();document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);status(`已下载：${a.download}`,'success')}
function startDrag(e){if(!S.crop)return;e.preventDefault();S.drag={id:e.pointerId,h:e.target.dataset.handle||'',x:e.clientX,y:e.clientY,c:{...S.crop}};E.box.setPointerCapture?.(e.pointerId)}
function moveDrag(e){const d=S.drag,b=S.bounds;if(!d||e.pointerId!==d.id||!b)return;e.preventDefault();const dx=e.clientX-d.x,dy=e.clientY-d.y,c=d.c,R=b.x+b.width,B=b.y+b.height;if(!d.h){S.crop={...c,x:clamp(c.x+dx,b.x,R-c.width),y:clamp(c.y+dy,b.y,B-c.height)}}else{const west=d.h.includes('w'),north=d.h.includes('n'),min=36;if(S.aspect){let delta=Math.abs(west?-dx:dx)>Math.abs((north?-dy:dy)*S.aspect)?(west?-dx:dx):(north?-dy:dy)*S.aspect;let w=Math.max(min,c.width+delta),maxH=north?c.y+c.height-b.y:B-c.y,maxW=west?c.x+c.width-b.x:R-c.x;w=Math.min(w,maxW,maxH*S.aspect);const h=w/S.aspect;S.crop={x:west?c.x+c.width-w:c.x,y:north?c.y+c.height-h:c.y,width:w,height:h}}else{let l=c.x,t=c.y,r=c.x+c.width,bot=c.y+c.height;if(west)l=clamp(c.x+dx,b.x,r-min);else r=clamp(r+dx,l+min,R);if(north)t=clamp(c.y+dy,b.y,bot-min);else bot=clamp(bot+dy,t+min,B);S.crop={x:l,y:t,width:r-l,height:bot-t}}}saveNorm();drawCrop()}
function endDrag(e){if(!S.drag||e.pointerId!==S.drag.id)return;S.drag=null;saveNorm();schedule()}
const open=()=>E.file.click();E.drop.onclick=open;E.emptyUpload.onclick=open;E.file.onchange=()=>load(E.file.files?.[0]).catch(e=>status(e.message,'error'));
['dragenter','dragover'].forEach(t=>E.drop.addEventListener(t,e=>{e.preventDefault();E.drop.classList.add('dragging')}));['dragleave','drop'].forEach(t=>E.drop.addEventListener(t,e=>{e.preventDefault();E.drop.classList.remove('dragging')}));E.drop.addEventListener('drop',e=>load(e.dataTransfer?.files?.[0]));
E.ratios.onclick=e=>{const b=e.target.closest('.ratio-btn');if(b)aspect(b.dataset.aspect,b)};E.w.oninput=()=>dim('w');E.h.oninput=()=>dim('h');E.lock.onchange=()=>{const w=Number(E.w.value),h=Number(E.h.value);if(w&&h)S.outRatio=w/h};$$('input[name="format"]').forEach(r=>r.onchange=schedule);E.quality.oninput=schedule;E.keep.onchange=()=>{if(!S.file)return;E.name.disabled=E.keep.checked;if(E.keep.checked)E.name.value=cleanName(S.file.name)};E.presets.onclick=e=>{const b=e.target.closest('button[data-width]');if(b)preset(b)};E.box.onpointerdown=startDrag;window.addEventListener('pointermove',moveDrag,{passive:false});window.addEventListener('pointerup',endDrag);window.addEventListener('pointercancel',endDrag);E.reset.onclick=()=>resetCrop();E.fit.onclick=()=>{S.norm=null;S.bounds=bounds();resetCrop()};E.clear.onclick=()=>clear();E.download.onclick=download;
new ResizeObserver(()=>{if(!S.file)return;const n=S.norm?{...S.norm}:null;S.bounds=bounds();S.norm=n;if(!restore())resetCrop(false);schedule()}).observe(E.stage);
window.addEventListener('beforeunload',()=>{if(S.srcUrl)URL.revokeObjectURL(S.srcUrl);if(S.previewUrl)URL.revokeObjectURL(S.previewUrl)});summary();
